#!/usr/bin/env bash
#MISE description="Create python mise preset"
#MISE dir="{{cwd}}"
mise use uv
mise tasks add format \
  --hide \
  -- uv format
mise tasks add lint \
  --hide \
  -- uvx ruff check
mise tasks add check \
  --depends "format" --depends "lint" \
  --description "Check python project" \
  -- uvx ty check
mise tasks add lint_fix -- \
  uvx ruff check --fix --exit-zero --output-format=concise --unsafe-fixes
mise tasks add type_fix -- \
  uvx ty check --fix --exit-zero --output-format=concise --unsafe-fixes
mise tasks add check \
  --depends "lint_fix" --depends "type_fix" \
  --description "Fix python project" \
  -- uvx pyrefly infer
