default:
    @just --list

nrfutil-flash hex_file snr:
    @nrfutil device program --serial-number {{ snr }} --firmware {{ join(invocation_directory(), hex_file) }} --options chip_erase_mode=ERASE_ALL,reset=RESET_SYSTEM

nrfutil-snr:
    @nrfutil device list --json --skip-overhead | jq -r '.devices[].serialNumber'
