jlink_flash_commands := '''
    r
    LE
    loadfile HEX
    r
    g
    writeDP 1 0
    readDP 1
    '''
jlink_reset_commands := '''
    r
'''
#Rpico2 has a VTOR_ADDR of 0x10000200
jlink-verify-command := '''
    r
    h
    mem32 VTOR_ADDR
    '''

default:
    @just --list


##### J-Link Documentation #####
jlink_notes_path := "/home/alealfaro/Documents/Obsidian/Embedded-Cpp-Notes/Build,Test and other tools/JLink/JLinkCommander_Notes.md"

# Show J-Link command documentation
show-jlink-commands:
    @bat --style=header,grid --paging=always {{jlink_notes_path}}
##### JLink Common #####
# Hidden recipe to run JLinkExe with common options
_jlink-run device script iface='swd' speed='4000' *extra_opts:
    @JLinkExe \
        -device "{{device}}" \
        -if "{{iface}}" \
        -speed "{{speed}}" \
        -CommanderScript "{{script}}" \
        -nogui 1 \
        -ExitOnError 1 \
        {{extra_opts}}

##### JLink flashing #####
jlink_flash_script_tmp_path := join(cache_directory(), "jlink.flash.tmp")

# Flash a hex file using J-Link.
flash-jlink device hex_file erase='true' reset='true' *extra_opts:
    #!/usr/bin/env bash
    set -euo pipefail
    script_path="{{jlink_flash_script_tmp_path}}"
    echo "" > "$script_path"
    if [[ "{{reset}}" == "true" ]]; then
        echo "r" >> "$script_path"
    fi
    if [[ "{{erase}}" == "true" ]]; then
        echo "erase" >> "$script_path"
    fi
    echo "loadfile \"{{hex_file}}\"" >> "$script_path"
    echo "q" >> "$script_path"

    @echo "INFO: Flashing {{hex_file}} to {{device}}"...
    @just _jlink-run "{{device}}" "$script_path" extra_opts="{{extra_opts}}"

# Reset the target using J-Link
jlink_reset_script_tmp_path := join(cache_directory(), "jlink.reset.tmp")
reset-jlink device:
    @echo "r\nq" > {{jlink_reset_script_tmp_path}}
    @echo "INFO: Resetting {{device}}"...
    @just _jlink-run "{{device}}" "{{jlink_reset_script_tmp_path}}"


jlink_verify_script_tmp_path := join(cache_directory(), "jlink.verify.tmp")
# Verify flash content by reading memory with J-Link
verify-flash-jlink device:
    @echo "r\nh\nmem32 0x10000200 4\nq" > {{jlink_verify_script_tmp_path}}
    @echo "INFO: Verifying flash on {{device}}"...
    @just _jlink-run "{{device}}" "{{jlink_verify_script_tmp_path}}"


##### J-Link Probe Actions #####
jlink_action_script_tmp_path := join(cache_directory(), "jlink.action.tmp")
_jlink-run-action script *extra_opts:
    @JLinkExe \
        -CommanderScript "{{script}}" \
        -nogui 1 \
        -ExitOnError 1 \
        {{extra_opts}}

jlink_5v_power_command := '''
    power <STATE>
    q
'''
# Toggle target power. State must be 'on' or 'off'.
power-jlink state:
    {{  if state =~ 'on&&off' { error('Invalid state') } else { '' } }}
    @echo "{{ replace(jlink_5v_power_command, '<STATE>', state) }}"  > "{{jlink_action_script_tmp_path}}"
    @echo "INFO: Turning target power {{state}}"
    @just _jlink-run-action "{{jlink_action_script_tmp_path}}"

jlink_vcom_command := '''
    VCOM <STATE>
    q
'''
# Toggle VCOM. State must be 'enable' or 'disable'.
vcom-jlink state:
    {{  if state =~ 'enable&&disable' { error('Invalid state') } else { '' } }}
    @echo "{{ replace(jlink_vcom_command, '<STATE>', state) }}"  > "{{jlink_action_script_tmp_path}}"
    @echo "INFO: Setting VCOM to {{state}}. Power-cycle the J-Link probe for change to take effect."
    @just _jlink-run-action "{{jlink_action_script_tmp_path}}"

jlink_status_command := '''
    st
    f
    q
'''
# Show J-Link hardware and firmware status
status-jlink:
    @echo "{{ jlink_status_command }}"  > "{{jlink_action_script_tmp_path}}"
    @echo "INFO: Getting status"
    @just _jlink-run-action "{{jlink_action_script_tmp_path}}"



##### Debugging #####
gdb_executable := "arm-none-eabi-gdb" # or arm-none-eabi-gdb, etc.
jlink_gdb_port := "2331"
# # Hidden recipe for GDB client
_debug-client-gdb elf_file port remote_cmd='target remote' *extra_opts:
    @echo "Starting GDB client for {{elf_file}}, connecting to localhost:{{port}}"
    {{gdb_executable}} \
        "{{elf_file}}" \
        -ex "{{remote_cmd}} localhost:{{port}}" \
        -ex "monitor halt" \
        -ex "monitor reset" \
        -ex "load" \
        {{extra_opts}}

##### J-Link Debugging #####


# Start J-Link GDB server
debug-server-jlink device iface="swd" speed="auto" port=jlink_gdb_port *extra_opts:
    @echo "Starting J-Link GDB server on port {{port}} for device {{device}}"
    @JLinkGDBServer \
        -device "{{device}}" \
        -if "{{iface}}" \
        -speed "{{speed}}" \
        -port "{{port}}" \
        -silent \
        -singlerun \
        {{extra_opts}}
