#!/usr/bin/env zsh
diff=$(git diff --cached | head -n 10)
if [ -z "$diff" ]; then
    echo "No changes in staging. Add changes first."
    exit 1
fi

local -r message=$(
    cat <<-EOF
        Please suggest a commit messages, given the following diff and using the template below,
        this is a non-interactive session, the message you output will be the one written to the commit message editor
        so be to the point and add any problems to the beggining of the message with a clear sign that something went wrong.

        **Output Format**
        Follow this output format and ONLY output raw commit messages without spacing, numbers or other decorations:
        <type>(<scope>): <description>.

        **Example**
        fix(app): add password regex pattern
        test(unit): add new test cases
        style: remove unused imports
        refactor(pages): extract common code to utils/wait.ts

        **Changes to analyze:**
        \$(git diff --cached --stat)
        \$(git diff --cached)


    **Recent Commits on Repo for Reference:**
    \$(git log -n 10 --pretty=format:'%h %s')
EOF
)
codex e -o /tmp/commit_msg "$message"
git commit -e -F /tmp/commit_msg
