#!/usr/bin/env zsh
acli_query=$(
  cat <<-EOF
project IN (BEDR, CWP, FWP)
AND assignee = currentUser()
AND status NOT IN (Done, Closed, Deprecated, Canceled)
ORDER BY created DESC
EOF
)
jq_query=$(
  cat <<-EOF
.[] | [
  .key,
  "\(.fields | .issuetype.name, .status.name)",
  "\(.key)-\(.fields.summary | ascii_downcase | gsub("[^a-z0-9 -]"; "") | gsub(" +"; "-"))"
] | @tsv
EOF
)

mise x acli -- \
  acli jira workitem search --jql "$acli_query" --fields "key,summary,status,issuetype" --json |
  jq -r "$jq_query"
