# $schema: https://mise.jdx.dev/schema/mise.json
[settings]
experimental = true
lockfile = true
color_theme = "dracula"
unix_default_file_shell_args = 'zsh -eu'
unix_default_inline_shell_args = "zsh -eu -c"
trusted_config_paths = [
  '~/sibel/eng/fw/anne-workspace',
  "~/sibel/Documents/Obsidian",
  "~/dotfiles/",
]
# tools can read the versions files used by other version managers
# for example, .nvmrc in the case of node's nvm
idiomatic_version_file_enable_tools = ['python']
disable_backends = ["asdf"]
# configure `mise install` to always keep the downloaded archive
always_keep_download = false # deleted after install by default
always_keep_install = false  # deleted on failure by default

# configure how frequently (in minutes) to fetch updated plugin repository changes
# this is updated whenever a new runtime is installed
# (note: this isn't currently implemented but there are plans to add it: https://github.com/jdx/mise/discussions/6735)
plugin_autoupdate_last_check_duration = '1 week'                                               # set to 0 to disable updates
status = { missing_tools = "if_other_versions_installed", show_env = true, show_tools = true }
task = { output = "interleave", run_auto_install = true, timings = true }
npm.package_manager = "bun"
npm.bun = true
pipx.uvx = true
python.uv_venv_auto = "source"
disable_tools = ["pipx:west"]


[settings.github]
gh_cli_tokens = true

[settings.cargo]
binstall_native = true
binstall = true

[tools]
jqp = "latest"
lua = "5.5"
dprint = "latest"
lua-language-server = "latest"
stylua = "latest"
lazygit = "latest"
usage = "latest"
claude-code = "latest"
cmake = "4.3.3"
tree-sitter = "latest"
ast-grep = "latest"
tmux = "latest"
ccache = "latest"
neovim = "0.12"
marksman = "latest"
shfmt = "latest"
shellcheck = "latest"
acli = "latest"
lazydocker = "latest"
jq = "latest"
uv = "latest"
"pipx:pyrefly" = "latest"
"pipx:ruff" = "latest"
"pipx:ty" = "latest"
"pipx:ptpython" = "latest"
"pipx:kconfigstyle" = "latest"

bun = "latest"
"npm:prettier" = "latest"
"npm:bash-language-server" = "latest"
"npm:yaml-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:defuddle" = "latest"
"npm:typescript-language-server" = "latest"
"npm:devicetree-language-server" = "latest"

gh = "latest"
git-lfs = "3.7.1"
"github:clangd/clangd" = "latest"
"github:joshmedeski/sesh" = "latest"
"github:dlvhdr/diffnav" = "latest"
"github:dandavison/delta" = "latest"
"github:apple/pkl-lsp" = "latest"

go = "latest"
"go:github.com/coolamit/mermaid-cli/cmd/mmd-cli" = "0.1.1"

rust = "latest"
rust-analyzer = "latest"
"cargo:taplo-cli" = "latest"
"cargo:neocmakelsp" = "latest"
"cargo:tlrc" = "latest"

"http:nrfutil" = { version = "1.4.0", url = "https://files.nordicsemi.com/artifactory/swtools/external/nrfutil/executables/{{arch(x64='x86_64')}}-{{os(linux='unknown-linux-gnu')}}/nrfutil" }
rg = "latest"
"vfox-zephyr:west" = "1.5.0"
difftastic = "latest"
yq = "latest"
hk = "latest"
actionlint = "1.7.12"
node = "latest"
sd = "latest"
opam = { version = "latest", asset_pattern = "opam-*-{gnu_arch}-{os}" }
pkl = "latest"
ninja = "latest"
"cargo:scope-monitor" = "latest"
"pipx:gersemi" = "latest"
worktrunk = "latest"
"vfox-zephyr:arm" = "latest"
"github:renode/renode" = "latest"

[plugins]
"vfox:zephyr" = "https://github.com/ale-alfaro/vfox-zephyr-sdk.git"


[tool_alias]
"python@3.12" = "python"

[task_templates."twister:testplan"]
description = "Save a testplan to a json file"
dir = "{{cwd}}"
vars.testplan_flag = "--save-tests"
usage = '''
arg "<platform>" {
  help "Platform"
  env "TWISTER_PLATFORM"
}
arg "<dir>" {
  help "Testsuite root"
  env "TWISTER_TESTSUITE_ROOT"
  default "."
}
flag "-t --testplan <testplan>" {
  help "Test plan json file"
  default "testplan.json"
}
arg "[extra_args]" {
  help "Extra args for twister"
  var #true
}
'''
run = '''
west twister -c --detailed-test-id {{ usage.extra_args | join(sep=" ") }} -p {{usage.platform}} -T {{usage.dir}} {{vars.testplan_flag}} {{usage.testplan}}
'''

[task_templates."twister:info"]
vars.info_flag = "--list-tests"
description = "Get info on twister-discoverable test using {{vars.info_flag}}"
dir = "{{cwd}}"
usage = '''
arg "<platform>" {
  help "Platform"
  env "TWISTER_PLATFORM"
}
arg "<dir>" {
  help "Testsuite root"
  env "TWISTER_TESTSUITE_ROOT"
  default "."
}
'''
run = '''
west twister -v -c \
  -p {{usage.platform}} \
  -T {{usage.dir}} \
  {{vars.info_flag}}
'''
