
[settings]
status = {
  missing_tools = "if_other_versions_installed",
show_env = true,
show_tools = true,
}
experimental = true
python.uv_venv_auto = "source"
# unix_default_file_shell_args = 'zsh -uc'
unix_default_inline_shell_args = 'zsh -uc'
trusted_config_paths = ['~/sibel/eng/fw', '~/sibel/eng/tools']
verbose = false                                                # set to true to see full installation output, see `MISE_VERBOSE`
http_timeout = "30s"                                           # set the timeout for http requests as duration string, see `MISE_HTTP_TIMEOUT`
jobs = 4                                                       # number of plugins or runtimes to install in parallel. The default is `4`.
yes = false                                                    # set to true to automatically answer yes to all prompts
not_found_auto_install = true                                  # see MISE_NOT_FOUND_AUTO_INSTALL
task_output = "prefix"                                         # see Tasks Runner for more information
env_shell_expand = true
use_file_shell_for_executable_tasks = true
# task.show_full_cmd = true


[tools]
python = ["latest", "3.13"]
uv = "latest"
usage = "latest"
atuin = "latest"
claude-code = "latest"
cmake = "latest"
codex = "latest"
starship = "latest"
tree-sitter = "latest"
"github:alltuner/mise-completions-sync" = "latest"
"pipx:docling" = "latest"
"pipx:ptpython" = "latest"
"pipx:pudb" = "latest"
"pipx:pyrefly" = "latest"
"pipx:ruff" = "latest"
"pipx:ty" = "latest"
node = "latest"
"npm:prettier" = "latest"
"npm:bash-language-server" = "latest"
"npm:yaml-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
ast-grep = "latest"
"pipx:cmakelang" = { version = "latest", extras = "yaml,html-gen" }
"pipx:clang-format" = "latest"
"pipx:dtsh" = "0.2.5"
tmux = "latest"
