#!/usr/bin/env zsh

###############################
# EXPORT ENVIRONMENT VARIABLE #
###############################

#export TERM='rxvt-256color'

# XDG
export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$HOME/.local/share
export XDG_STATE_HOME=$HOME/.local/state
export XDG_CACHE_HOME=$HOME/.cache

# Set up default editor
# ------------------------------------------------------------------------------
# editor
export EDITOR="nvim"
export VISUAL="nvim"
export SUDO_EDITOR="$EDITOR"
export FCEDIT="$EDITOR"

export NVIM_HOME="$HOME/.local/nvim"
# zsh
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTFILE="$XDG_DATA_HOME/zsh/history"
export HISTSIZE=25001 # Maximum events for internal history
export SAVEHIST=25001 # Maximum events in history file

# export KEYTIMEOUT=1

# Man pages
export MANPAGER='nvim +Man!'

local -r FZF_PREVIEW="if [ -d {} ]; then eza --tree --color=always {} | head -200; else bat -n --color=always --line-range :500 {}; fi"

FZF_COLORS="bg+:#3B4252, \
      bg:#2E3440,\
      spinner:#81A1C1,\
      hl:#616E88,\
      fg:#D8DEE9,\
      header:#616E88,\
      info:#81A1C1,\
      pointer:red,\
      marker:red,\
      fg+:#D8DEE9,\
      prompt:#81A1C1,\
      hl+:red"

export FZF_DEFAULT_OPTS="--height 60% \
--border sharp \
--layout reverse \
--color '$FZF_COLORS' \
--prompt '∷ ' \
--pointer ▶ \
--marker ⇒"

export FZF_CTRL_T_OPTS="
      $FZF_DEFAULT_OPTS
      --preview '$FZF_PREVIEW'
      "
export FZF_ALT_C_OPTS="
    --walker-skip .git,node_modules,target
    --preview 'eza -lh --group-directories-first --icons=auto {}'
    --height=80%
    --bind 'ctrl-/:change-preview-window(down|hidden|)'
    --header 'CTRL-/: Toggle preview window position'
"
# golang
export GOROOT="/usr/local/go"
export GOPATH="$HOME/go"
export JUST_HOME="$XDG_CONFIG_HOME/just"
export EMBEDDER_BIN="/home/alealfaro/.embedder/bin"
# PATH
export PATH="$GOROOT/bin:$GOPATH/bin:$HOME/.local/bin:$HOME/.cargo/bin:$PATH:$EMBEDDER_BIN"
