#!/usr/bin/env just --justfile

set unstable := true
set shell := ["bash", "-eou", "pipefail", "-c"]

default:
    @just -g --list

bat-files-with-extension extension search_base_directory=".":
    @fd --extension {{extension}} --base-directory {{search_base_directory}} -X bat --style=header --paging=never

bat-files-with-glob glob search_base_directory=".":
    @fd --glob {{glob}} --base-directory {{search_base_directory}} -X bat --style=header --paging=never

systemd-diagnostics:
    @systemctl status --full --no-pager > systemd-status.log
    @systemctl --failed --no-pager > systemd-failed.log
    @awk 'NR==2 {print $2}' systemd-status.log | xargs systemctl status --full --no-pager
    @awk 'NR==2 {print $2}' systemd-status.log | xargs journalctl --no-pager

addr2line-bat elf addr:
    @arm-none-eabi-addr2line -p -e {{elf} {{addr} | awk '{ file_line=$NF; if (match(file_line, /:[0-9]+$/)) { line=substr(file_line,
     RSTART+1); file=substr(file_line, 1, RSTART-1); start=line-10; if (start < 1) start = 1; end=line+10; system("bat --line-range " start ":" end " --highlight-line " line " " file) } }'
