#Not using snr, needed for multiple jlinks
# serial_number := env('SNR_VAR') || '728343547'
#--west-flash="--dev-id=${SNR_VAR}"

default:
    @just --list

zephyr_base := env('ZEPHYR_BASE')
requirements_txt := if path_exists(source_dir() / "requirements-twister.txt") == "true" { source_dir() / "requirements-twister.txt" } else { zephyr_base / "scripts" / "requirements-base.txt" }
twister := "uv run --no-project --python=3.13 --with-requirements " + requirements_txt + " west twister"
twister_report_flags := "--report-dir samples/shell_hil/twister_report --outdir samples/shell_hil/twister_out"
twister_verbose_flags := env('TWISTER_VERBOSITY', '-v')
twister_default_flags := twister_verbose_flags + " --allow-installed-plugin --clobber-output --no-detailed-test-id "

[group('twister')]
[no-cd]
twister_run test_root platform *args:
    {{ twister }} \
    {{ twister_default_flags }} \
      -p {{ platform }} \
      -T {{ test_root }} \
      {{ args }}

[group('twister')]
[no-cd]
twister_run_scenario test_root platform scenario *args:
    {{ twister }} \
    {{ twister_default_flags }} \
      -p {{ platform }} \
      -T {{ test_root }} \
      -s {{ scenario }} \
      {{ args }}

[group('twister')]
[no-cd]
prep-test test_root board: (twister_run board test_root "--prep-artifacts-for-testing")

native_sim_west_flags := "-b native_sim -- -DCONFIG_UART_NATIVE_PTY_0_ON_STDINOUT=y"
qemu_west_flags := "-b qemu_x86 -- -DQEMU_PIPE=qemu-fifo"
hardware_twister_flags := "--west-flash=--skip-rebuld --enable-slow --device-testing --device-serial=" + env('SERIAL_PORT', '/dev/ttyACM0')

[group('twister')]
[no-cd]
run-hw-test test_root $BOARD *args: (twister_run "$BOARD" test_root hardware_twister_flags + ' ' + args)

[group('twister')]
[no-cd]
twister_run_sim test_root *args: (twister_run test_root "native_sim" args)

[group('twister')]
[no-cd]
twister_run_serial test_root $BOARD *args:
    just twister_run {{ test_root }} {{ "$BOARD" }} "{{ hardware_twister_flags }} {{ args }}"

pytest_base_opts := "--strict-markers --strict-config -ra --log-cli-level='INFO' "
pytest_debug_opts := "-v -s -log-cli-level='DEBUG' "
pytest_zephyr_opts := " --twister-harness --build-dir=build  --device-serial=" + env('SERIAL_PORT', '/dev/ttyACM0')
pytest := if env('UV_PYTHON', "") != "" { "uv run pytest" } else { "pytest" }

_pytest_run *args:
    {{ pytest }} {{ pytest_base_opts }} {{ args }}

_pytest_run_debug $PYTHONASYNCIODEBUG="1" *args:
    {{ pytest }} {{ pytest_debug_opts }} {{ args }}

[group('pytest')]
[no-cd]
pytest_run platform *args:
    just _pytest_run  {{ pytest_zephyr_opts + " " + append(platform, " --device-type=") }} "{{ args }}"

[group('pytest')]
[no-cd]
pytest_run_shell *args: (pytest_run "hardware" args)
