gtags_parser (comma separated list)

    Specify the mapping of language names and plug-in parsers. Each part delimited by the comma consists of a language name, a colon, the shared object path, an optional colon followed by a function name. If the function name is not specified, ’parser’ is assumed. As a special exception, gtags collects values from multiple gtags_parser variables. For these mappings, the first match is adopted.
gtags_hook (command line)

    Specify a command line which should be executed at the beginning of gtags after loading configuration file. You can use this hook to update gtags.files dynamically. "./" in it always means the project root directory, since gtags is always invoked there.
    This hook is ignored when the following options are specified: –version, –help, –config, –dump.
icase_path (boolean)

    Ignore case distinctions in the path. Suffixes check is affected by this capability.
langmap (comma separated list)

    Language mapping. Each comma-separated map consists of a language name, a colon, and a list of file extensions. You can specify a glob pattern surrounded by parentheses instead of an extension for the files without extensions (e.g. Make:([Mm]akefile).mak.mk). As a special exception, gtags collects values from multiple langmap variables. For these mappings, the first match is adopted. Default mapping is:
    ‘c:.c.h,yacc:.y,asm:.s.S,java:.java,cpp:.c++.cc.hh.cpp.cxx.hxx.hpp.C.H,php:.php.php3.phtml’.
skip (comma separated list)

    Gtags skips files and directories which are given in this list. As a special exception, gtags collects values from multiple skip variables. If the value ends with ‘/’, it is assumed as a directory and gtags skips all files under it. The value may include glob patterns (*, ?, [...], [!...], [^...]).
    If the value starts with ‘/’, it is assumed a relative path name from the root directory of the project. You cannot use glob patterns for a path name. However, this direction is out-of-date, and is not recommended. Instead, you can use ‘-f’ option which can be combined with find(1). Since find(1) has rich options to select files, you can do everything. Additionally, this technique can also be applied to any other tagging systems like ctags(1), cscope(1), etc.
    Skip list is also effective when you use the ‘-f’ or gtags.files.
