set unstable := true
set allow-duplicate-recipes := true
set shell := ["zsh", "-uc"]

justfile_home := config_dir() / 'just'

mod openocd
mod direnv
mod zephyr
mod nordic

# @_:
#     just --list-heading '{{ BOLD + RED }}{{ "\n" + file_stem(source_directory()) + ":\n" }}{{ NORMAL }}' --list

@_:
    fd . {{ justfile_home }} --extension=just -d 1 -x \
      just --color=always \
      --list {/.} \
      --justfile {{ justfile_home / 'Justfile' }} \
      --list-heading='{{ "{/.}:" + "\n\n" }}'

@list_all:
    fd . {{ justfile_home }} --extension=just -d 1 -x \
      just --justfile {}
