set unstable := true
set allow-duplicate-recipes := true
set shell := ["zsh", "-uc"]

mod python
mod gnu-stow
mod JLink
mod openocd
mod arch-linux
mod git

@_:
    @just --summary --unsorted
    @just --list
