set unstable := true
set allow-duplicate-recipes := true
set shell := ["zsh", "-uc"]

justfile_home := config_dir() / 'just'

mod agents
mod python
mod JLink
mod openocd
mod git
mod direnv
mod zephyr
mod nordic
mod ozone

[default]
@list_mods:
    fd . {{ justfile_home }} --extension=just -d 1 -x \
      just --color=always \
      --list {/.} \
      --justfile {{ justfile_home / 'Justfile' }} \
      --list-heading='{{ "{/.}:" + "\n\n" }}'

@list_all:
    fd . {{ justfile_home }} --extension=just -d 1 -x \
      just --justfile {}
