#!/usr/bin/env just --justfile --working-directory `pwd`

set shell := ["bash", "-c"]
set unstable := true
set allow-duplicate-recipes := true

export west := if env('UV_PYTHON', "") != "" { "uv run west" } else { "west" }

import 'dtsh.just'
import 'test/justfile'

mod test

default:
    @just --list

# initialize west
[group('zephyr')]
[no-cd]
init:
    @west init -l config
    @west update --fetch-opt=--filter=blob:none
    @west zephyr-export

# update west
[group('zephyr')]
[no-cd]
update:
    @west update --fetch-opt=--filter=blob:none

[group('zephyr')]
setup-nrfutil:
    #!/usr/bin/env bash
    echo "Setting up nrfutil"
    echo "Checking if nrfutil is installed"
    if command -v nrfutil &> /dev/null 2>&1; then
        echo "nrfutil already exists"
    else
        echo "Downloading nrfutil"
        curl https://files.nordicsemi.com/artifactory/swtools/external/nrfutil/executables/x86_64-unknown-linux-gnu/nrfutil -o nrfutil
        chmod +x nrfutil
        mv nrfutil /usr/local/bin
    fi
    nrfutil install completion device nrf5sdk-tools toolchain-manager sdk-manager

[group('zephyr')]
install-tooling:
    pip install -U dtsh #DTS viewer in terminal

[group('debugging')]
[no-cd]
west-boards *filter:
    @echo "Getting all boards available"
    @west boards -f "{name}#_#_#{dir}#_#_{qualifiers}" | awk -v cwd="$(pwd)/" -F '#_#_#' 'BEGIN {print "| Board | Path | Qualifiers |"; print "|---|---|---|" } {{ filter }} { sub(cwd, "", $2); gsub(/^[ \t]+|[ \t]+$/, "", $1); gsub(/^[ \t]+|[ \t]+$/, "", $2); gsub(/^[ \t]+|[ \t]+$/, "", $3); print "| " $1 " | " $2 " | " $3 " |"}'

[group('zephyr')]
[no-cd]
west-boards-filter-by-path path="app":
    just west-boards '$2 ~ /\/{{ path }}\// '

# Flash with runner. Supported runners: uf2 (default) or jlink
# [group('zephyr')]
# flash build_dir runner="jlink":
#     @ {{ if runner == "uf2" { "sudo" } else { "" } }} uv run west flash -r {{ runner }} -d {{ build_dir }}

[group('debugging')]
[no-cd]
rtt:
    @west rtt -r jlink

[group('lifecycle')]
[no-cd]
build app_dir board *extra:
    {{ west }} build --pristine=always -b {{ board }}  -s {{ app_dir }} -d "{{ app_dir }}/build" {{ if is_dependency() == "false" { extra } else { "" } }}
    {{ if is_dependency() == "true" { extra } else { "" } }}

[group('lifecycle')]
[no-cd]
build_full app_dir board artifact extra_conf="" extra_dtc="":
    {{ west }} build --pristine=always -b {{ board }}  -s {{ app_dir }} -d {{ app_dir / "build_" + artifact }}  \
                  {{ if extra_conf != "" { '--extra-conf ' + extra_conf } else { "" } }} \
                  {{ if extra_dtc != "" { '--extra-dtc-overlay ' + extra_dtc } else { "" } }} \
                  {{ if env('SHIELD', "") != "" { '--shield ' + env('SHIELD') } else { "" } }} \
                  {{ if env('SNIPPET', "") != "" { '--S ' + env('SNIPPET') } else { "" } }}

default_runner := if env('BOARD', "") =~ "^nrf5" { "nrfutil" } else { "jlink" }

[group('lifecycle')]
[no-cd]
flash build_dir runner=default_runner:
    @echo "flashing with runner {{ runner }}"
    {{ west }} flash -r {{ runner }} -d {{ build_dir }}
