#!/usr/bin/env just --justfile --working-directory `pwd`

set shell := ["bash", "-c"]

# full_board_name_cmd := 'west boards -f "{name}/{qualifiers}"  --name "$1"'

set unstable := true
set allow-duplicate-recipes := true

west-topdir := env('WEST_TOPDIR', shell('topdir=$(west topdir)'))
zephyr_base := env('ZEPHYR_BASE', ```
    topdir=$(west topdir)
    zephyr_base="$(realpath $topdir)/$(west config zephyr.base)"
    echo $zephyr_base
```)
export west := if env('UV_PYTHON', "") != "" { "uv run west" } else { "west" }

# default_hex_file := "build/zephyr/zephyr.hex"

import 'dtsh.just'
import 'build.just'
import 'test/justfile'

mod test

default:
    @just --list

# initialize west
[group('zephyr')]
init:
    @west init -l config
    @west update --fetch-opt=--filter=blob:none
    @west zephyr-export

# update west
[group('zephyr')]
update:
    @west update --fetch-opt=--filter=blob:none

[group('zephyr')]
setup-nrfutil:
    #!/usr/bin/env bash
    echo "Setting up nrfutil"
    echo "Checking if nrfutil is installed"
    if command -v nrfutil &> /dev/null 2>&1; then
        echo "nrfutil already exists"
    else
        echo "Downloading nrfutil"
        curl https://files.nordicsemi.com/artifactory/swtools/external/nrfutil/executables/x86_64-unknown-linux-gnu/nrfutil -o nrfutil
        chmod +x nrfutil
        mv nrfutil /usr/local/bin
    fi
    nrfutil install completion device nrf5sdk-tools toolchain-manager sdk-manager

[group('zephyr')]
install-tooling:
    pip install -U dtsh #DTS viewer in terminal

[group('debugging')]
[no-cd]
west-boards *filter:
    @echo "Getting all boards available"
    @west boards -f "{name}#_#_#{dir}#_#_{qualifiers}" | awk -v cwd="$(pwd)/" -F '#_#_#' 'BEGIN {print "| Board | Path | Qualifiers |"; print "|---|---|---|" } {{ filter }} { sub(cwd, "", $2); gsub(/^[ \t]+|[ \t]+$/, "", $1); gsub(/^[ \t]+|[ \t]+$/, "", $2); gsub(/^[ \t]+|[ \t]+$/, "", $3); print "| " $1 " | " $2 " | " $3 " |"}'

[group('zephyr')]
west-boards-filter-by-path path="app":
    just west-boards '$2 ~ /\/{{ path }}\// '

# Flash with runner. Supported runners: uf2 (default) or jlink
# [group('zephyr')]
# flash build_dir runner="jlink":
#     @ {{ if runner == "uf2" { "sudo" } else { "" } }} uv run west flash -r {{ runner }} -d {{ build_dir }}

[group('debugging')]
rtt:
    @west rtt -r jlink

[group('lifecycle')]
[no-cd]
build app_dir board *args:
    {{ west }} build --pristine=always -b {{ board }} {{ args }} -s {{ app_dir }} -d "{{ app_dir }}/build"

default_runner := if env('BOARD', "") =~ "^nrf5" { "nrfutil" } else { "jlink" }

[group('lifecycle')]
[no-cd]
flash build_dir runner=default_runner:
    @echo "flashing with runner {{ runner }}"
    {{ west }} flash -r {{ runner }} -d {{ build_dir }}
