#!/usr/bin/env just --justfile --working-directory `pwd`

set shell := ["bash", "-c"]
set unstable := true
set allow-duplicate-recipes := true

uv_run := "uv run " + env('VIRTUAL_ENV', '') && "--active "
west := uv_run + "west "

import 'dtsh.just'
import 'test/justfile'
import 'lifecycle.just'

default:
    @just --list

# initialize west
[group('zephyr')]
[no-cd]
init west_yaml:
    @west init -l {{ west_yaml }}
    @west update --fetch-opt=--filter=blob:none
    @west zephyr-export

# update west
[group('zephyr')]
[no-cd]
update:
    @west update --fetch-opt=--filter=blob:none

[group('zephyr')]
setup-nrfutil:
    #!/usr/bin/env bash
    echo "Setting up nrfutil"
    echo "Checking if nrfutil is installed"
    if command -v nrfutil &> /dev/null 2>&1; then
        echo "nrfutil already exists"
    else
        echo "Downloading nrfutil"
        curl https://files.nordicsemi.com/artifactory/swtools/external/nrfutil/executables/x86_64-unknown-linux-gnu/nrfutil -o nrfutil
        chmod +x nrfutil
        mv nrfutil /usr/local/bin
    fi
    nrfutil install completion device nrf5sdk-tools toolchain-manager sdk-manager

[group('zephyr')]
install-tooling:
    pip install -U dtsh #DTS viewer in terminal

[group('debugging')]
[no-cd]
west-boards *filter:
    @echo "Getting all boards available"
    @west boards -f "{name}#_#_#{dir}#_#_{qualifiers}" | awk -v cwd="$(pwd)/" -F '#_#_#' 'BEGIN {print "| Board | Path | Qualifiers |"; print "|---|---|---|" } {{ filter }} { sub(cwd, "", $2); gsub(/^[ \t]+|[ \t]+$/, "", $1); gsub(/^[ \t]+|[ \t]+$/, "", $2); gsub(/^[ \t]+|[ \t]+$/, "", $3); print "| " $1 " | " $2 " | " $3 " |"}'

[group('zephyr')]
[no-cd]
west-boards-filter-by-path path="app":
    just west-boards '$2 ~ /\/{{ path }}\// '
