# Only display the OSD on the currently focused monitor
$osdclient = swayosd-client --monitor "$(hyprctl monitors -j | jq -r '.[] | select(.focused == true).name')"

# Laptop multimedia keys for volume and LCD brightness (with OSD)
bindeld = ,F11, Volume up, exec, $osdclient --output-volume raise
bindeld = ,F10, Volume down, exec, $osdclient --output-volume lower
bindeld = ,F9, Mute, exec, $osdclient --output-volume mute-toggle
bindeld = ,F4, Brightness up, exec, $osdclient --brightness raise
bindeld = ,F3, Brightness down, exec, $osdclient --brightness lower

# Precise 1% multimedia adjustments with Alt modifier
bindeld = ALT, F11, Volume up precise, exec, $osdclient --output-volume +1
bindeld = ALT, F10, Volume down precise, exec, $osdclient --output-volume -1
bindeld = ALT, F4, Brightness up precise, exec, $osdclient --brightness +1
bindeld = ALT, F3, Brightness down precise, exec, $osdclient --brightness -1

# Requires playerctl
bindld = , F8, Next track, exec, $osdclient --playerctl next
bindld = , F7, Pause, exec, $osdclient --playerctl play-pause
bindld = , F6, Previous track, exec, $osdclient --playerctl previous

