# Change the default Omarchy look'n'feel

source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
source = ~/.local/share/omarchy/default/hypr/windows.conf
source = ~/.config/omarchy/current/theme/hyprland.conf
# https://wiki.hypr.land/Configuring/Basics/Variables/#general
general {
    # No gaps between windows or borders
    # gaps_in = 0
    # gaps_out = 0
    # border_size = 0

    # Change to niri-like side-scrolling layout
    # layout = scrolling
}

# https://wiki.hypr.land/Configuring/Basics/Variables/#decoration
decoration {
    # Use round window corners
    rounding = 8

    # Dim unfocused windows (0.0 = no dim, 1.0 = fully dimmed)
    dim_inactive = true
    dim_strength = 0.15
}

# https://wiki.hypr.land/Configuring/Basics/Variables/#animations
animations {
    # Disable all animations
    # enabled = no
}

# https://wiki.hypr.land/Configuring/Basics/Variables/#layout
layout {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}


# Bitwarden vault login:
windowrule = match:class (chrome-)(.*), match:initial_title (_crx_)(.*), center on, float on, size 500 600

# File dialogs:
windowrule = match:class xdg-desktop-portal-gtk, center on float on size 900 600
windowrule = match:class zen, match:title (Open|Save) Files, center on, float on, size 900 550

# New mail window:
windowrule = match:class (.*)Thunderbird, match:title ^Write(.*), float on, size 800 600

# PWAs:
windowrule = match:class (zen)(.*), match:initial_title Element, center on, float on, size 1100 780
