# Bar, wallpaper
exec-once = uwsm app -- hyprsunset 
# exec-once = uwsm-app -- hypridle #idle manager disabled as it was causeing crashes
exec-once = uwsm app -- mako #Notification daemon
exec-once = uwsm app -- waybar
exec-once = uwsm app -- fcitx5
exec-once = uwsm app -- swaybg -i ~/.config/omarchy/current/background -m fill
exec-once = uwsm app -- swayosd-server
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = uwsm-app -- elephant
exec-once = uwsm app -- walker --gapplication-service
