

# See https://wiki.hyprland.org/Configuring/Monitors/
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale
# You must relaunch Hyprland after changing any envs (use Super+Esc, then Relaunch)

# Optimized for retina-class 2x displays, like 13" 2.8K, 27" 5K, 32" 6K.
env = GDK_SCALE,2
# hyprlang if THINKPAD_LAPTOP
# Monitor for laptop
monitorv2 {
  output = eDP-1,
  mode = preferred
  position = auto-left
  scale = auto
}
# Additional monitor for laptop
monitorv2 {
  output = HDMI-A-1
  mode = preferred
  position = auto-right
  scale = auto
}

workspace = 1,monitor:eDP-1,rounding:true,decorate:true,gapsin:1,gapsout:8
workspace = 2,monitor:eDP-1,rounding:true,decorate:true,gapsin:1,gapsout:8
workspace = 3,monitor:eDP-1,rounding:true,decorate:true,gapsin:1,gapsout:8
workspace = 4,monitor:HDMI-A-1,rounding:true,decorate:true,gapsin:0,gapsout:0
workspace = 5,monitor:HDMI-A-1,rounding:true,decorate:true,gapsin:0,gapsout:0
workspace = 6,monitor:HDMI-A-1,rounding:true,decorate:true,gapsin:0,gapsout:0
#hyprlang endif

# hyprlang if DESKTOP
# Monitors for desktop
monitorv2 {
  output = HDMI-A-1
  mode = preferred
  position = auto-left
  scale = auto
}
monitorv2 {
  output = HDMI-A-2
  mode = preferred
  position = auto-right
  scale = auto
}
workspace = 1,monitor:HDMI-A-1,rounding:true,decorate:true,gapsin:1,gapsout:8
workspace = 2,monitor:HDMI-A-1,rounding:true,decorate:true,gapsin:1,gapsout:8
workspace = 3,monitor:HDMI-A-1,rounding:true,decorate:true,gapsin:1,gapsout:8
workspace = 4,monitor:HDMI-A-2,rounding:true,decorate:true,gapsin:0,gapsout:0
workspace = 5,monitor:HDMI-A-2,rounding:true,decorate:true,gapsin:0,gapsout:0
workspace = 6,monitor:HDMI-A-2,rounding:true,decorate:true,gapsin:0,gapsout:0

# hyprlang endif
