# ######## Window rules ########
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
windowrule = suppressevent maximize, class:.*

# Just dash of opacity by default
windowrule = opacity 0.97 0.9, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

windowrule = bordercolor rgb(FF0000) rgb(880808), workspace:4
windowrule = bordercolor rgb(FF0000) rgb(880808), workspace:5
windowrule = bordercolor rgb(FF0000) rgb(880808), workspace:6



# App-specific tweaks
source = ~/.local/share/omarchy/default/hypr/apps.conf
windowrule = tag +terminal, class:org.wezfurlong.wezterm
