# ######## Window rules ########

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
windowrule = suppressevent maximize, class:.*

# Just dash of opacity by default
windowrule = opacity 0.97 0.9, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0


source = monitors.conf


### Example rules
# windowrule = move 100 100, class:kitty                                    # Move kitty to 100 100
# windowrule = animation popin, class:kitty                                 # Set the animation style for kitty
# windowrule = noblur, class:firefox                                        # Disable blur for firefox
# windowrule = move cursor -50% -50%, class:kitty                           # Move kitty to the center of the cursor
# windowrule = bordercolor rgb(FF0000) rgb(880808), fullscreen:1            # Set bordercolor to red if window is fullscreen
# windowrule = bordercolor rgb(00FF00), fullscreenstate:* 1                 # Set bordercolor to green if window's client fullscreen state is 1(maximize) (internal state can be anything)
# windowrule= bordercolor rgb(FFFF00), title:.*Hyprland.*                  # Set bordercolor to yellow when title contains Hyprland
# windowrule = opacity 1.0 override 0.5 override 0.8 override, class:kitty  # Set opacity to 1.0 active, 0.5 inactive and 0.8 fullscreen for kitty
# windowrule = rounding 10, class:kitty                                     # Set rounding to 10 for kitty
# windowrule = stayfocused,  class:(pinentry-)(.*)                          # Fix pinentry losing focus

windowrule = bordercolor rgb(FF0000) rgb(880808), workspace:4
windowrule = bordercolor rgb(FF0000) rgb(880808), workspace:5
windowrule = bordercolor rgb(FF0000) rgb(880808), workspace:6
# windowrule = bordercolor rgb(FF0000) rgb(880808), workspace:9
# windowrule = bordercolor rgb(FF0000) rgb(880808), workspace:10



# App-specific tweaks
source = ~/.local/share/omarchy/default/hypr/apps.conf
