MiniClue.enable_buf_triggers(0)
MiniDiff.disable(0)
local bufnr = vim.api.nvim_get_current_buf()
vim.api.nvim_buf_set_keymap(bufnr, 'n', 'h[', '<Cmd>lua require("codediff").prev_hunk()<CR>', { desc = 'Prev Hunk' })
vim.api.nvim_buf_set_keymap(bufnr, 'n', 'h]', '<Cmd>lua require("codediff").next_hunk()<CR>', { desc = 'Next Hunk' })
vim.api.nvim_buf_set_keymap(bufnr, 'n', 'f[', '<Cmd>lua require("codediff").prev_file()<CR>', { desc = 'Prev File' })
vim.api.nvim_buf_set_keymap(bufnr, 'n', 'f]', '<Cmd>lua require("codediff").next_file()<CR>', { desc = 'Next File' })
-- vim.api.nvim_buf_del_keymap(bufnr, 'n', 'h[')
-- vim.api.nvim_buf_del_keymap(bufnr, 'n', 'h]')
-- vim.api.nvim_buf_del_keymap(bufnr, 'x', 'h[')
-- vim.api.nvim_buf_del_keymap(bufnr, 'x', 'h]')
