-- local M = {}
--
-- local neoconf = require 'neoconf'
--
-- function M.get_autosave()
--   local settings = neoconf.get('codecompanion.history', { autosave = true })
--   return settings.autosave
-- end
--
-- function M.toggle_and_save_autosave()
--   local current_autosave = M.get_autosave()
--   local new_autosave = not current_autosave
--   neoconf.set('codecompanion.history.autosave', new_autosave)
--   vim.notify('CodeCompanion History autosave: ' .. tostring(new_autosave), vim.log.levels.INFO)
-- end
--
-- return {
--
--   {
--     'folke/neoconf.nvim',
--   },
--   {
--
--     dependencies = {
--       'neoconf',
--       'codecompanion.history',
--     },
--     opts = function(_, opts)
--       vim.api.nvim_create_user_command('CodeCompanionHistoryToggleAutosave', function()
--         require('custom.codecompanion_history_config').toggle_and_save_autosave()
--       end, { desc = 'Toggle CodeCompanion History autosave' })
--       local defaults = {
--         doit = true,
--         count = 1,
--         array = {},
--       }
--
--       opts.extensions.history = {
--         ---Automatically generate titles for new chats
--         auto_generate_title = false,
--         continue_last_chat = false,
--         delete_on_clearing_chat = false,
--       }
--       -- register your settings schema with Neodev, so auto-completion will work in the json files
--       require('neoconf.plugins').register {
--         on_schema = function(schema)
--           -- this call will create a json schema based on the lua types of your default settings
--           schema:import('myplugin', defaults)
--           -- Optionally update some of the json schema
--           schema:set('myplugin.array', {
--             description = 'Special array containing booleans or numbers',
--             anyOf = {
--               { type = 'boolean' },
--               { type = 'integer' },
--             },
--           })
--         end,
--       }
--
--       local my_settings = Neoconf.get('neodev', defaults)
--     end,
--     keys = {
--
--       { '<leader>aH', '<cmd>CodeCompanionHistoryToggleAutosave<cr>', desc = 'Toggle CodeCompanion History Autosave' },
--     },
--   },
-- }
