
[task_templates."west:build"]
dir = "{{cwd}}"
description = "Build a zephyr app with west"
usage = '''
arg "<app>" help="App to build" env="ZEPHYR_APP"
flag "-b --board <board>"  {
    help "Board to run sample on"
    env "BOARD"
}
flag "-S --snippet <snippet>" {
    help "Select a snippet to apply"
    env "SNIPPET"
}
flag "-c --clean" help="Clean"
flag "-i --interactive" help="Interactive"
flag "-o --out <out>" {
    help "Build directory name where to output the files when doing a clean rebuild"
}
arg "[cmake_opts]" var=#true
'''
run = '''
#!/usr/bin/env zsh
set -euxo pipefail
is_sysbuild=$(west config build.sysbuild 2>1)
if [[ ! -z ${usage_board:-} ]]; then
    board="${usage_board:?}"
elif [[ ! -z ${usage_interactive:-} ]]; then
    board="$(west boards | fzf)"
fi

if [[ ! -z ${usage_snippet:-} ]]; then
    snippet="${usage_snippet}"
elif [[ ! -z ${usage_interactive:-} ]]; then
    snippet=$(west -q forall -c "fd 'snippet.yml' . -x yq e '.name'" | fzf)
fi

eval "usage_cmake_args=(${usage_cmake_opts:-})"
if [[ -n "${usage_cmake_args?}" ]]; then
    for arg in ${usage_cmake_args?}; do
        cmake_args+=" -D${arg?}"
    done
fi

cmd=$(cat <<EOF
west build \
${=${usage_board:+-b ${usage_board?}}} \
${usage_app?} \
${(z)${usage_out:+-d ${usage_out?}}} \
${usage_clean:+-p} \
${(z)${cmake_args:+-- ${cmake_args[@]}}}
EOF
)
echo "Running build cmd $cmd"
eval "$cmd"
echo "Successfull build. Output files written to ${usage_out:-build}/"
'''

[task_templates."west:flash"]
dir = "{{cwd}}"
description = "Flash"
usage = '''
arg "<app>" help="App to build" env="ZEPHYR_APP"
flag "-c --context" help="Get runner's context info"
flag "-e --erase" help="Do full erase"
flag "--rtt" help="Connect to device RTT console after flashing"
'''
run = '''
build_dir="build_${usage_app:t}"
[[ ! -z ${usage_erase:-} ]] && runner_flags="--erase"
[[ ! -d "${build_dir}" ]] && echo "Directory ${build_dir} doesnt exist" && exit 1
if [[ ! -z ${usage_context:-} ]]; then
  west flash -d ${build_dir}   -H -r ${usage_runner?}
else
  echo "Flashing Device"
  west flash -d ${build_dir?} ${runner_flags:-} --reset
  if [[ ! -z ${usage_rtt:-} ]]; then
    echo "Connecting to RTT in 3 seconds"
    sleep 3
    west rtt -d ${build_dir?}
  fi
fi
'''

[task_templates."west:debug"]
description = "Debug"
env = { _.path = "/opt/zephyr-sdk-custom/arm-zephyr-eabi/bin" }
dir = "{{cwd}}"
usage = '''
arg "[app]" help="Application" env="ZEPHYR_APP"
flag "-d --domain [domain]" help="Domain"
'''
run = '''
app_name=${usage_app:t}
west attach --gdb ${ARM_GDB_PY?} --domain ${usage_domain:-$app_name} -d "build_${app_name}"
'''


[task_templates."test:info"]
description = "Get the test tree and list of tags from Zephyr twister test runner"
dir = "{{config_root}}"
usage = '''
arg "[test_dir]" help="Test application directory" env="TWISTER_TEST_DIR"
'''
run = '''
test_dir="${usage_test_dir?}"
west twister -T  ${test_dir} --test-tree
west twister -T ${test_dir} --list-tags
'''

[task_templates."test:list"]
description = "Lists the test suite testcases"
dir = "{{config_root}}"
usage = '''
arg "[test_dir]" help="Test application directory" env="TWISTER_TEST_DIR"
'''
run = '''
west twister -T ${usage_test_dir?} --list-tests --log-level=ERROR
'''

[task_templates."test:prep"]
description = "Prep the test artifacts for Zephyr twister test runner"
dir = "{{config_root}}"
usage = '''
arg "[test_dir]" help="Test application directory" env="TWISTER_TEST_DIR"
flag "-b --board <board>" help="Board to test with. Will be used as the platform in Twister" env="BOARD"
arg "<twister_args>" help="Twister arguments" env="TWISTER_ARGS" var=#true double_dash="required"
'''
run = '''
west twister \
    --platform ${usage_board?} \
    -T ${usage_test_dir?} \
    --prep-artifacts-for-testing \
    ${(z)${usage_twister_args:+${usage_twister_args[@]}}}
'''
