# Run linters
[group('qa')]
[no-cd]
lint_ruff *args:
    uvx ruff check --fix {{ args }}
    uvx ruff format

lint_ruff_unsafe *args:
    uvx ruff check --fix --unsafe-fixes {{ args }}
    uvx ruff format

uv_run_flags := env('UV_RUN_FLAGS', "--all-packages")
uv_sync_flags := env('UV_SYNC_FLAGS', "--dev --all-packages")

# Check types
[group('qa')]
[no-cd]
typing_ty *ty_flags:
    uv run {{ uv_run_flags }} ty check {{ ty_flags }}

[group('qa')]
[no-cd]
typing_basedpyright *basedpyright_flags:
    uv run {{ uv_run_flags }}  basedpyright  {{ basedpyright_flags }}

[group('qa')]
[no-cd]
typing_mypy package_list *mypy_flags:
    uv run mypy  {{ package_list }} {{ mypy_flags }}

# Update dependencies
[group('lifecycle')]
[no-cd]
update:
    uv sync --upgrade {{ uv_sync_flags }}

[group('lifecycle')]
[no-cd]
install python_semver="3.13":
    uv venv "--python={{ python_semver }}"
    uv sync {{ uv_sync_flags }}
    @echo "Installing pre-commit hook"
    @uv run prek install

# Remove temporary files
[group('lifecycle')]
[no-cd]
clean:
    rm -rf .venv .pytest_cache .mypy_cache .ruff_cache
    find . -type d -name "__pycache__" -exec rm -r {} +

# Recreate project virtualenv from nothing
[group('lifecycle')]
[no-cd]
fresh: clean install
