# yaml-language-server: $schema=https://gh-dash.dev/schema.json
prSections:
  - title: Mine
    filters: >-
      is:open author:@me
    layout:
      author:
        hidden: true
  - title: Review
    filters: >-
      is:open review-requested:@me
    layout:
      repo:
        width: 6
  - title: Personal
    filters: >-
      is:open user:@me
  - title: Sibel Subscribed
    filters: >-
      is:open repo:sibelhealth/sh_sdk_2.0 repo:sibelhealth/sensors-app
      repo:sibelhealth/BengalFly-Zephyr repo:sibelhealth/DragonFly-Zephyr
issuesSections:
  - title: Creator
    filters: author:@me
  - title: Commented
    filters: is:open commenter:@me
  - title: Assigned
    filters: is:open assignee:@me
defaults:
  view: prs
  refetchIntervalMinutes: 10
  layout:
    prs:
      repoName:
        grow: true,
        width: 10
        hidden: false
      base:
        hidden: true
  preview:
    open: true
    width: 80
  prsLimit: 20
  issuesLimit: 20
repoPaths:
  ale-alfaro/*: ~/sibel/eng/tools/*
  sibelhealth/DragonFly-Zephyr: ~/sibel/eng/fw/anne_sensors_workspace/dragonfly
  sibelhealth/BengalTiger-Zephyr: ~/sibel/eng/fw/anne_sensors_workspace/bengal
  sibelhealth/framework: ~/sibel/eng/fw/anne_sensors_workspace/framework
  sibelhealth/sh_sdk_2.0: ~/sibel/eng/fw/anne_sensors_workspace/sh_sdk_2_0
  ale-alfaro/dotfiles: ~/dotfiles
keybindings:
  universal:
    - key: g
      name: lazygit
      command: >
        cd {{.RepoPath}} && lazygit
  prs:
    - key: O
      name: code review
      command: >-
        tmux new-window -n "enhance" '
          gh enhance -R {{.RepoName}} {{.PrNumber}}
        '
    - key: v
      name: approve
      command: >
        gh pr review --repo {{.RepoName}} --approve --body "$(gum input
        --prompt='Approval Comment: ')" {{.PrNumber}}
    - key: r
      name: Run Workflow
      command: >
        gh workflow run "$(gh workflow list --json path --jq '.' | jq -r
        '.[].path | ltrimstr(".github/workflows/")' | fzf)"
        --ref={{.HeadRefName}}

  notifications:
    - key: d
      builtin: markAsDone
    - key: D
      builtin: markAllAsDone
theme:
  ui:
    sectionsShowCount: true
    table:
      compact: false
      showSeparator: true
  colors:
    text:
      primary: "#E2E1ED"
      secondary: "#666CA6"
      inverted: "#242347"
      faint: "#B0B3BF"
      warning: "#E0AF68"
      error: "#DB4B4B"
      success: "#3DF294"
    background:
      selected: "#1B1B33"
    border:
      primary: "#383B5B"
      secondary: "#39386B"
      faint: "#2B2B40"
pager:
  diff: diffnav
repo:
  branchesRefetchIntervalSeconds: 30
  prsRefetchIntervalSeconds: 60
showAuthorIcons: true
smartFilteringAtLaunch: false
