# general.import = [ "~/.config/hypr/current/theme/alacritty.toml" ]
general.import = [ "~/.config/alacritty/themes/omarchy_tokio_night.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "Adwaita Mono" }
bold = { family = "Adwaita Mono" }
italic = { family = "Adwaita Mono" }

size = 9
# size = 18

[window]
padding.x = 14
padding.y = 14
decorations = "None"

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]

[terminal]
# shell = { program = "/bin/zellij" }
shell = { program = "/bin/zsh", args = ["-l"] }
