-- Handle the output of the recipe and push to the quickfix list
--
-- TODO: there is no way to determine what type of output is generated
-- solely by running the recipe and therefore no way to add a meaningful
-- entry to the quickfix list.
--
-- The 'errorformat' option specifies a list of formats that are recognized.
-- The first match is being used.
-- One take on that is to just concatenate all the error formats and hope for the best
-- This approach would have the least control on how the errors are handled, except they
-- are parsed from the just recipes. This would allow to have fine control over
-- what error format is generated by what recipe. This is maybe the easiest approach to try.
-- Another approach would be to have just output a unified error format and set the error format in neovim to that...
local jobs = require 'custom.just.jobs'

local M = {}

---Clears the quickfix window.
local function clearQuickfix()
  vim.fn.setqflist({}, 'r')
end

---Sets the quickfix list title.
---@param arg any Title of the quickfix window.
local function setQuickfixTitle(arg)
  vim.fn.setqflist({}, 'a', {
    title = arg,
  })
end

local function completeRecipe(args)
  -- Match the command line arguments to all the available recipes and sugges
  -- those that contain the arguments
  local justRecipes = jobs.justSummary()
  if not justRecipes then
    return {}
  end
  local suggestionList = {}
  for _, recipe in pairs(justRecipes) do
    if string.find(recipe, args) then
      table.insert(suggestionList, recipe)
    end
  end

  return suggestionList
end

M.setup = function(_)
  vim.api.nvim_create_user_command('Just', function(args)
    -- No parameter passed
    if not args.fargs[1] then
      VimRc.info(jobs.justList())
      return
    end

    -- TODO handle multiple arguments
    local recipeName = args.fargs[1]

    clearQuickfix()
    setQuickfixTitle('Just recipe: ' .. args.fargs[1])
    jobs.justRunAsync(recipeName, true)
  end, {
    nargs = '*',
    complete = completeRecipe,
  })

  vim.api.nvim_create_user_command('J', function(args)
    local justRecipes = jobs.justSummary()
    if not justRecipes then
      return
    end
    FzfLua.fzf_exec(justRecipes, {
      cwd_only = true,
      actions = {
        ['default'] = function(selected)
          jobs.justRunAsync(selected[1], true)
        end,
      },
      complete = true,
    })
  end, { desc = 'Just Recipe' })
end

return M
