-- Handle the output of the recipe and push to the quickfix list
--
-- TODO: there is no way to determine what type of output is generated
-- solely by running the recipe and therefore no way to add a meaningful
-- entry to the quickfix list.
--
-- The 'errorformat' option specifies a list of formats that are recognized.
-- The first match is being used.
-- One take on that is to just concatenate all the error formats and hope for the best
-- This approach would have the least control on how the errors are handled, except they
-- are parsed from the just recipes. This would allow to have fine control over
-- what error format is generated by what recipe. This is maybe the easiest approach to try.
-- Another approach would be to have just output a unified error format and set the error format in neovim to that...
local jobs = require 'custom.just.jobs'

local utils = require 'custom.just.utils'

local M = {}

local function completeRecipe(args)
  -- Match the command line arguments to all the available recipes and sugges
  -- those that contain the arguments
  local justRecipes = jobs.justSummary()
  if not justRecipes then
    return {}
  end
  local suggestionList = {}
  for _, recipe in pairs(justRecipes) do
    if string.find(recipe, args) then
      table.insert(suggestionList, recipe)
    end
  end

  return suggestionList
end

M.setup = function(_)
  vim.api.nvim_create_user_command('Just', function(args)
    -- No parameter passed
    if not args.fargs[1] then
      utils.printTable(jobs.justList())
      return
    end

    -- TODO handle multiple arguments
    local recipeName = args.fargs[1]

    utils.clearQuickfix()
    utils.setQuickfixTitle('Just recipe: ' .. args.fargs[1])
    jobs.justRunAsync(recipeName, true)
  end, {
    nargs = '*',
    complete = completeRecipe,
  })
end

require('fzf-lua').live_grep {
  cmd = 'git grep --ignore-case --extended-regexp --line-number --column --color=always --untracked',
  fn_transform_cmd = function(query, cmd, _)
    -- Extract search query and glob string separated by '--'
    local search_query, glob_str = query:match '(.-)%s-%-%-(.*)'

    if not glob_str then
      return -- Fallback to original command if no glob string
    end

    -- Convert glob string into git-compatible pathspecs
    local pathspecs = {}
    for pattern in glob_str:gmatch '%S+' do
      if pattern:sub(1, 1) == '!' then
        -- Convert '!pattern' to git's exclude pathspec
        table.insert(pathspecs, string.format("':(exclude)%s'", pattern:sub(2)))
      else
        table.insert(pathspecs, string.format("'%s'", pattern))
      end
    end

    -- Compose the final git grep command
    local new_cmd = string.format('%s %s %s', cmd, vim.fn.shellescape(search_query), table.concat(pathspecs, ' '))
    return new_cmd, search_query
  end,
}
return M
