-- Handle the output of the recipe and push to the quickfix list
--
-- TODO: there is no way to determine what type of output is generated
-- solely by running the recipe and therefore no way to add a meaningful
-- entry to the quickfix list.
--
-- The 'errorformat' option specifies a list of formats that are recognized.
-- The first match is being used.
-- One take on that is to just concatenate all the error formats and hope for the best
-- This approach would have the least control on how the errors are handled, except they
-- are parsed from the just recipes. This would allow to have fine control over
-- what error format is generated by what recipe. This is maybe the easiest approach to try.
-- Another approach would be to have just output a unified error format and set the error format in neovim to that...
local jobs = require 'custom.just.jobs'

local utils = require 'custom.just.utils'

local M = {}

local function completeRecipe(args)
  -- Match the command line arguments to all the available recipes and sugges
  -- those that contain the arguments
  local justRecipes = jobs.justSummary()
  if not justRecipes then
    return {}
  end
  local suggestionList = {}
  for _, recipe in pairs(justRecipes) do
    if string.find(recipe, args) then
      table.insert(suggestionList, recipe)
    end
  end

  return suggestionList
end

M.setup = function(_)
  vim.api.nvim_create_user_command('Just', function(args)
    -- No parameter passed
    if not args.fargs[1] then
      utils.printTable(jobs.justList())
      return
    end

    -- TODO handle multiple arguments
    local recipeName = args.fargs[1]

    utils.clearQuickfix()
    utils.setQuickfixTitle('Just recipe: ' .. args.fargs[1])
    jobs.justRunAsync(recipeName, true)
  end, {
    nargs = '*',
    complete = completeRecipe,
  })
end
M.fzf_dirs = function(opts)
  local fzf_lua = require 'fzf-lua'
  opts = opts or {}
  opts.prompt = 'Just Recipes> '
  opts.fn_transform = function(x)
    return fzf_lua.utils.ansi_codes.magenta(x)
  end
  opts.actions = {
    ['default'] = function(selected)
      vim.cmd('just ' .. selected[1])
    end,
  }
  fzf_lua.fzf_exec("just --summary --unsorted | tr ' ' '\n' ", opts)
end
M.recipePicker = function(opts)
  opts = opts or {}

  pickers
    .new(opts, {
      prompt_tile = 'Just Recipes',
      finder = finders.new_table(jobs.justSummary()),
      sorter = config.generic_sorter(opts),
      attach_mappings = function(prompt_bufnr, _)
        -- Select Default
        actions.select_default:replace(function()
          actions.close(prompt_bufnr)
          local selection = action_state.get_selected_entry()
          jobs.justRunAsync(selection[1])
        end)
        return true
      end,
    })
    :find()
end
return M
