local M = {}

M.supported = {
	"append",
	"bookmark",
	"bookmarks",
	"daily",
	"delete",
	"diff",
	"file",
	"files",
	"folder",
	"folders",
	"move",
	"orphans",
	"outline",
	"prepend",
	"properties",
	["property"] = { "read", "remove", "set" },
	"read",
	"rename",
	"restart",
	"search",
	"task",
	"tasks",
	["template"] = { "read", "insert" },
	["templater"] = { "create-from-template" },
	"templates",
	"tag",
	"tags",
	"vault",
	"vaults",
	"web",
}

---Completable arguments per CLI command.
---Entries ending with `=` are key=value params, bare entries are flags.
---@type table<string, string[]>
M.args = {
	append = { "file=", "path=", "content=", "inline" },
	bookmark = { "file=", "subpath=", "folder=", "search=", "url=", "title=" },
	bookmarks = { "total", "verbose", "format=" },
	daily = { "paneType=" },
	delete = { "file=", "path=", "permanent" },
	diff = { "file=", "path=", "from=", "to=", "filter=" },
	file = { "file=", "path=" },
	files = { "folder=", "ext=", "total" },
	folder = { "path=", "info=" },
	folders = { "folder=", "total" },
	move = { "file=", "path=", "to=" },
	orphans = { "total", "all" },
	outline = { "file=", "path=", "format=", "total" },
	prepend = { "file=", "path=", "content=", "inline" },
	properties = { "file=", "path=", "name=", "total", "sort=", "counts", "format=", "active" },
	["property:read"] = { "name=", "file=", "path=" },
	["property:remove"] = { "name=", "file=", "path=" },
	["property:set"] = { "name=", "value=", "type=", "file=", "path=" },
	read = { "file=", "path=" },
	rename = { "file=", "path=", "name=" },
	restart = {},
	search = { "query=", "path=", "limit=", "total", "case", "format=" },
	task = { "ref=", "file=", "path=", "line=", "toggle", "done", "todo", "daily", "status=" },
	tasks = { "file=", "path=", "total", "done", "todo", "status=", "verbose", "format=", "active", "daily" },
	["template:read"] = { "name=", "resolve", "title=" },
	["template:insert"] = { "name=" },
	["templater:create-from-template"] = { "template=", "file=", "open" },
	templates = { "total" },
	tag = { "name=", "total", "verbose" },
	tags = { "file=", "path=", "total", "counts", "sort=", "format=", "active" },
	vault = { "info=" },
	vaults = { "total", "verbose" },
	web = { "url=", "newtab" },
}

return M
