
[pyinfer]
description = "Pyrefly type infer and auto annotate types"
run = "pyrefly infer"

[pylint]
description = "Ruff lint and fix"
run = "ruff check --fix --exit-zero --output-format=concise --unsafe-fixes"

[pyfix]
dir = "{{config_root}}/common/.config/gdb"
description = "Run pyrefly type infer and ruff check fix"
run = [{ task = "lint_fix" }, { task = "type_infer" }]
