

[stow_generic]
description = "Stow generic task"
hide = true
vars = { target_dir = "{{xdg_config_home}}", pkgs = ".config" }
usage = '''
arg "[pkg_dir]" help="Package root dir" {
  default "."
  env "STOW_PKG_DIR"
}
arg "[stow_op]" help="Stow operation to do with packages" {
  choices "stow" "restow" "unstow"
  default "restow"
}
'''
run = '''
#!/usr/bin/env zsh
set -euxo pipefail
if [[ ! -z ${STOW_NO_SIM:-} && ${STOW_NO_SIM} = 1 ]]; then
  sim_flag=""
else
  sim_flag="--simulate"
fi
case ${usage_stow_op?} in
  stow) op_flag="-S" ;;
  restow) op_flag="-R" ;;
  unstow) op_flag="-D" ;;
  *) echo "Invalid operation!" && exit 1 ;;
esac

stow -d ${usage_pkg_dir?} -t {{vars.target_dir}} --verbose=${VERBOSE_LVL:-2} ${sim_flag?} ${op_flag?} {{vars.pkgs}}
'''

#
# [group('stow')]
# @stow-check-bogus target_dir:
#     chkstow -b -t {{ target_dir }}
#
# [group('maintanance')]
# @restow-platform-dotfiles: (restow dots / os() conf_home '.config')
#     echo "Stowed {{ os() }} packages"
#
# [group('maintanance')]
# [macos]
# restow-zshenv: (restow dots / "common/home" home_dir() '.')
#
# [linux]
# [working-directory(x'${HOME}/dotfiles/linux/etc')]
# restow-etc:
#     sudo ln -sf -t /etc/pacman.d $(realpath pacman.d/mirrorlist*)
#     sudo ln -sf -t /etc/pacman.d $(realpath pacman.d/hooks)
#     sudo ln -sf -t /etc/pacman.d $(realpath pacman.d/gnupg)
#     sudo ln -sf -t /etc/zsh $(realpath zsh/*)
#     sudo ln -sf -t /etc/nix $(realpath nix/*)
#
# [linux]
# restow-applications: (restow dots / os() data_local_dir() 'applications')
#
# @restow-user-bin: (restow dots / "common" executable_dir() 'bin')
#
# @restow-common-dotfiles: (restow dots / 'common' conf_home '.config')
#
# restow-dotfiles: restow-common-dotfiles restow-platform-dotfiles
#
# agents_skills_src_dir := dots / 'common' / 'llm_memory' / 'skills'
# agents_skills_target_dir := home_dir() / '.agents' / 'skills'
#
# @stow-agents-skills: (sstow agents_skills_src_dir agents_skills_target_dir '.')
#
# # clean-bogus: Find and automatically remove all broken symlinks
# [group('stow')]
# clean-bogus target_dir:
#     @echo "Searching for and removing broken symlinks..."
#     @chkstow -b -t {{ target_dir }} | awk -F': ' '{print $2}' | xargs -r rm
#     @echo "✅ Done."
#
# # check-aliens: Find 'alien' files (not managed by stow) in the target directory
# [group('stow')]
# check-aliens target_dir:
#     @chkstow -a -t {{ target_dir }} | awk '{print $2}'
#
# # clean-aliens-interactive: Interactively remove 'alien' files. DANGEROUS!
# # This will prompt you to delete any file or directory in your .config
#
# # that is NOT a symlink created by stow. Use with extreme caution.
# [group('stow')]
# clean-aliens-interactive target_dir:
#     @echo "WARNING: This is a dangerous operation."
#     @echo "You will be prompted to delete every file not managed by stow."
#     @chkstow -a -t {{ target_dir }} | awk -F': ' '{print $2}' | xargs -r -p rm -rf
