
[task_templates."stow:platform"]
env = { STOW_PKG_DIR = "{{config_root}}/{{os()}}" }
run = { task = "stow_generic" }

[stow_platform_sim]
env = { VERBOSE_LVL = "2" }
hide = true
extends = "stow:platform"

[stow_platform_unsafe]
env = { STOW_NO_SIM = "1", VERBOSE_LVL = "0" }
hide = true
confirm = "Do you want to stow the common packages?"
extends = "stow:platform"

[stow_platform]
description = "Stow platform packages"
run = [{ task = "stow_platform_sim" }, { task = "stow_platform_unsafe" }]


[task_templates."stow:common"]
env = { STOW_PKG_DIR = "{{config_root}}/common", VERBOSE_LVL = "2" }
hide = true
run = { task = "stow_generic" }

[stow_common_sim]
extends = "stow:common"

[stow_common_unsafe]
env = { STOW_NO_SIM = "1", VERBOSE_LVL = "0" }
confirm = "Do you want to stow the common packages?"
extends = "stow:common"

[stow_common]
description = "Stow common packages"
run = [{ task = "stow_common_sim" }, { task = "stow_common_unsafe" }]
