

[task_templates."stow:config"]
env = { VERBOSE_LVL = 2, STOW_TARGET_DIR = "{{xdg_config_home}}", STOW_PKG_DIR = "{{config_root}}/common" }
run = [{ task = "stow_generic", args = [".config"] }]


[stow_common]
extends = "stow:config"

[stow_common_unsafe]
env = { STOW_PKG_DIR = "{{config_root}}/commmon", STOW_NO_SIM = "1", VERBOSE_LVL = "0" }
hide = true
confirm = "Do you want to stow the common packages?"
extends = "stow:config"


[stow_platform_sim]
env = { STOW_PKG_DIR = "{{config_root}}/{{os()}}" }
hide = true
extends = "stow:config"

[stow_platform_unsafe]
env = { STOW_PKG_DIR = "{{config_root}}/{{os()}}", STOW_NO_SIM = "1", VERBOSE_LVL = "0" }
hide = true
confirm = "Do you want to stow the platform packages?"
extends = "stow:config"
