#!/usr/bin/env zsh
set -euo pipefail
#MISE description="Stow dotfiles"
#MISE dir="{{env.HOME}}/dotfiles"
#USAGE arg "<pkg>" help="Package" default=".config"
#USAGE flag "--sim" help="Perform simulated operation instead of doing it"
#USAGE flag "--op [stow_op]" help="Stow operation to do with packages" {
#USAGE   choices "stow" "restow" "unstow"
#USAGE   default "restow"
#USAGE}
case ${usage_op?} in
  stow) op_flag="-S" ;;
  restow) op_flag="-R" ;;
  unstow) op_flag="-D" ;;
  *) echo "Invalid operation!" && exit 1 ;;
esac

case ${usage_pkg?} in
  .config) target="${XDG_CONFIG_HOME:-$HOME/.config}" ;;
  home) target="${HOME}" ;;
  bin) target="${HOME}/.local/bin" ;;
  *) echo "Invalid operation!" && exit 1 ;;
esac

common_flags=('-d' "common/${usage_pkg?}" '-t' "${target?}" "${(z)${usage_sim:+-vv --simulate}:-}" "${op_flag?}" '.')
stow "${common_flags[@]}"
platform_flags=('-d' "linux/${usage_pkg?}" '-t' "${target?}" "${(z)${usage_sim:+-vv --simulate}:-}" "${op_flag?}" '.')
stow "${platform_flags[@]}"
