

["global:github:secret:key-set"]
description = "Set a Github Secret"
dir = "{{cwd}}"
usage = '''
arg "<pem>"  help="Key PEM file"
'''
run = 'gh secret set --app codespaces --app actions {{usage.pem | file_stem | shoutysnakecase }} < {{usage.pem}}'

["global:github:gen-key"]
usage = 'arg "<repo>"'
hide = true
run = 'ssh-keygen -t ed25519 -C "git@github.com:sibelhealth/{{usage.repo}}.git"  -f ~/sibel-ci-keys/{{usage.repo}} -N ""'

["global:github:add-key-secret"]
dir = "{{cwd}}"
hide = true
usage = '''
arg "<keyfile>" help="Key File"
arg "<repo>" help="Repo"
'''
run = '''
if [[ ! -a {{usage.keyfile}} ]]; then
  echo "Keyfile {{usage.keyfile}} doesnt exist! Create a key using gen_deploy_key"
  exit 1
fi
gh secret set SSH_DEPLOY_KEY_{{usage.repo | shoutysnakecase}} < {{usage.keyfile}}
'''

# GitHub CLI api
# https://cli.github.com/manual/gh_api
["global:github:upload-key"]
usage = '''
flag "-R --remote <remote>"  {
    help "Repo in the format user/repo"
}
flag "--title [title]" {
    help "Title for deploy keys"
}
'''
hide = true
run = '''
gh api \
  --method POST \
  -H "Accept: application/vnd.github+json" \
  -H "X-GitHub-Api-Version: 2026-03-10" \
  '/repos/{{usage.remote}}/keys' \
   -f 'title={{usage.title}}' -f 'key={{ read_file(path=env.PUBKEY) | trim }}' \
    -F "read_only=true"
'''


["global:github:cs-pick-machine"]
description = "Pick default machine for codespaces for this repo"
dir = "{{cwd}}"
hide = true
run = '''
machine=$(gh api \
  -H "Accept: application/vnd.github+json" \
  -H "X-GitHub-Api-Version: 2026-03-10" \
  "/repos/${${$(git remote get-url origin)#https://github.com/*}%*.git}/codespaces/machines" | jq -r \
  '[.machines[] | pick(.name, .display_name)] | map("\(.name) : \(.display_name)") | .[]' |
  fzf --separator=':' --accept-nth 1
)
mise set CODESPACES_MACHINE="$machine"
'''

["global:github:cs-create"]
description = "Create codespaces for this repo and with the current branch"
usage = 'arg "<name>" help="display name"'
dir = "{{cwd}}"
hide = true
run = '''
gh cs create \
  -R $(print "${${$(git remote get-url origin)#https://github.com/*}%*.git}") \
  -b "$(git branch --show-current)" \
  --devcontainer-path .devcontainer/devcontainer.json \
  --location WestUs2 \
  --machine "${CODESPACES_MACHINE:-standardLinux32gb}" \
  --display-name {{usage.name}}
'''
