

["global:github:secret:key-set"]
description = "Set a Github Secret"
dir = "{{cwd}}"
usage = '''
arg "<pem>"  help="Key PEM file"
'''
run = 'gh secret set --app codespaces --app actions {{usage.pem | file_stem | shoutysnakecase }} < {{usage.pem}}'

["global:github:gen-key"]
usage = 'arg "<repo>"'
hide = true
run = 'ssh-keygen -t ed25519 -C "git@github.com:sibelhealth/{{usage.repo}}.git"  -f ~/sibel-ci-keys/{{usage.repo}} -N ""'

["global:github:add-key-secret"]
dir = "{{cwd}}"
hide = true
usage = '''
arg "<keyfile>" help="Key File"
arg "<repo>" help="Repo"
'''
run = '''
if [[ ! -a {{usage.keyfile}} ]]; then
  echo "Keyfile {{usage.keyfile}} doesnt exist! Create a key using gen_deploy_key"
  exit 1
fi
gh secret set SSH_DEPLOY_KEY_{{usage.repo | shoutysnakecase}} < {{usage.keyfile}}
'''

# GitHub CLI api
# https://cli.github.com/manual/gh_api

["global:github:deploy-keys"]
dir = "{{cwd}}"
usage = '''
flag "-R --remote <remote>" {
    help "Current remote/repo that will use the deploy key"
}
flag "-t --target <target>" {
    help "Target repo to add deploy key to"
}
flag "--title <title>" {
    help "Title for deploy keys"
}
flag "--read-only" {
    help "Permission level set to read-only otherwise write"
}
'''
hide = true
run = '''
keyfile="$(mktemp -u deploy-key-{{usage.remote | file_stem }}-{{usage.target | file_stem }}.XXXX)"
title="${usage_title:-}"
[[ -n "$title" ]] || title="Keys for CI usage in {{usage.remote}}"
# trap 'rm -f "$keyfile" "$keyfile.pub"' EXIT

ssh-keygen -t ed25519 -N "" -f "$keyfile" \
  -C "Deploy SSH Keys. Remote: {{usage.remote}} Target: {{usage.target}}"


gh secret set SSH_DEPLOY_KEY_{{usage.target | file_stem | shoutysnakecase}} \
  -R {{usage.remote}} < "$keyfile"

gh api --method POST \
  -H "Accept: application/vnd.github+json" \
  -H "X-GitHub-Api-Version: 2026-03-10" \
  "/repos/{{usage.target}}/keys" \
  -f "title=$title" \
  -f "key=$(<"$keyfile.pub")" \
  -F "read_only={% if usage.read-only %}true{% else %}false{% endif %}"
'''


["global:github:cs-pick-machine"]
description = "Pick default machine for codespaces for this repo"
dir = "{{cwd}}"
hide = true
run = '''
machine=$(gh api \
  -H "Accept: application/vnd.github+json" \
  -H "X-GitHub-Api-Version: 2026-03-10" \
  "/repos/${${$(git remote get-url origin)#https://github.com/*}%*.git}/codespaces/machines" | jq -r \
  '[.machines[] | pick(.name, .display_name)] | map("\(.name) : \(.display_name)") | .[]' |
  fzf --separator=':' --accept-nth 1
)
mise set CODESPACES_MACHINE="$machine"
'''

["global:github:cs-create"]
description = "Create codespaces for this repo and with the current branch"
usage = 'arg "<name>" help="display name"'
dir = "{{cwd}}"
hide = true
run = '''
gh cs create \
  -R $(print "${${$(git remote get-url origin)#https://github.com/*}%*.git}") \
  -b "$(git branch --show-current)" \
  --devcontainer-path .devcontainer/devcontainer.json \
  --location WestUs2 \
  --machine "${CODESPACES_MACHINE:-standardLinux32gb}" \
  --display-name {{usage.name}}
'''
