#!/usr/bin/env zsh
set -e
#MISE description="Control brightness, volume and playback on Arch Linux"
#MISE dir="{{cwd}}"
#MISE hide=true
#USAGE flag "--toggle [onoff]" help="Toggle playback or mute mic/speakers" {
#USAGE  choices "playback" "mic" "speakers"
#USAGE }
#USAGE arg "[ctl]" help="Brightness or volume control modifier" {
#USAGE  choices "bright" "vol"
#USAGE }
#USAGE arg "[scalar]" help="Modifier scalar for adjusting control"

# Start with the first possible output, then refine to the most likely given an order heuristic.
# Adjust brightness on the most likely display device.
# Usage: omarchy-brightness-display <step>
MONITOR="$(hyprctl monitors -j | jq -r '.[] | select(.focused == true).name')"

_swayosd_ctl() {
  swayosd-client --monitor "$MONITOR" "$@"
}

ctl="${usage_ctl:-${usage_onoff?}}"
case ${ctl} in
  bright)
    omarchy-brightness-display "${usage_scalar?}%"
    ;;
  vol)
    _swayosd_ctl --output-volume "${usage_scalar:-raise}"
    ;;
  play)
    _swayosd_ctl --playerctl play-pause
    ;;
  mic)
    _swayosd_ctl --input-volume mute-toggle
    ;;
  speakers)
    _swayosd_ctl --output-volume mute-toggle
    ;;
  *)
    ;;
esac
