["_artifacts:mergehex"]
description = "Merge mcuboot and app hex"
hide = true
dir = "{{cwd}}"
usage = 'arg "<build>" help="build dir"'
run = '''
uv run {{env.ZEPHYR_BASE | default(value='zephyr')}}/scripts/build/mergehex.py {{usage.build}}/**/zephyr/zephyr.signed.hex {{usage.build}}/mcuboot/zephyr/zephyr.hex -o merged.hex
if [[ -d {{usage.build}}/hci_ipc ]]; then
  cp {{usage.build}}/hci_ipc/zephyr/zephyr.hex merged_CPUNET.hex
fi
'''


["nrf5340:flash:sysbuild"]
description = "Flash both Network and Application Core FW"
dir = "{{cwd}}"
usage = '''
arg "<build_dir>" help="Build Dir"
flag "-s --serial [port]" help="Serial"
'''
run = '''
build_dir="${usage_build_dir?}"
domains="${build_dir}/domains.yaml"
[[ -f "${domains?}" ]] || {
  echo "No domains.yaml. Is this a sysbuild app?"
  exit 1
}
local -a flash_order_arr
flash_order_arr=(${(f)"$(yq e '.flash_order[]' $domains)"})
echo "${flash_order_arr[@]}"
for img in "$flash_order_arr[@]"; do
  hex="${build_dir}/${img}/zephyr/zephyr.hex"
  core="Application"
  if [[ $img == hci_ipc || $img == ipc_radio ]]; then 
    core="Network"
  fi
  [[ -f "${hex?}" ]] && nrfutil device program --core "${core?}" --firmware "${hex}"
done
sleep 2
nrfutil device reset
[[ -n "${usage_serial}" ]] && scope serial "${usage_serial}" 115200
'''
