["python:format"]
dir = "{{cwd}}"
run = "uv format"

["python:lint"]
depends = ["python:format"]
dir = "{{cwd}}"
usage = 'arg "[flags]" help="Flags" var=#true'
run = 'uvx ruff check "${(z)usage_flags:-.}"'

["python:typecheck"]
dir = "{{cwd}}"
usage = 'arg "[flags]" help="Flags" var=#true'
run = 'uvx ty check "${(z)usage_flags:-}"'
