


[_stow_dotfiles]
hide = true
dir = "{{env.HOME}}/dotfiles"
env = { VERBOSE_LVL = 2, STOW_TARGET_DIR = "{{xdg_config_home}}", STOW_PKG_DIR = "{{config_root}}/common" }
usage = '''
arg "<pkg>" help="Package types to stow" {
  choices "config" "home" "bin"
  default "config"
}
flag "--sim" help="Perform simulated operation instead of doing it"
'''
run = '''

case ${usage_pkg?} in
  config) target="${XDG_CONFIG_HOME:-$HOME/.config}" ;;
  home) target="${HOME}" ;;
  bin) target="${HOME}/.local/bin" ;;
  *) echo "Invalid operation!" && exit 1 ;;
esac

common_flags=('-d' "common/${usage_pkg?}" '-t' "${target?}" "${(z)${usage_sim:+-vv --simulate}:-}" "-R" '.')
stow "${common_flags[@]}"
platform_flags=('-d' "linux/${usage_pkg?}" '-t' "${target?}" "${(z)${usage_sim:+-vv --simulate}:-}" "-R" '.')
stow "${platform_flags[@]}"
'''

["stow:dry_run"]
description = "Stow dotfiles"
hide = true
usage = '''
arg "<pkg>" help="Package types to stow" {
  choices "config" "home" "bin"
  default "config"
}
'''
run = [
  { task = "_stow_dotfiles", args = [
    '{{usage.pkg}}',
    "--sim",
  ] },
  { task = "_stow_dotfiles", args = [
    '{{usage.pkg}}',
    "--sim",
  ], env = { STOW_PKG_DIR = "{{config_root}}/{{os()}}" } },
]


["stow:doftiles"]
description = "Stow dotfiles"
hide = true
usage = '''
arg "<pkg>" help="Package types to stow" {
  choices "config" "home" "bin"
  default "config"
}
'''
run = [
  { task = "_stow_dotfiles", args = [
    '{{usage.pkg}}',
  ] },
  { task = "_stow_dotfiles", args = [
    '{{usage.pkg}}',
  ], env = { STOW_PKG_DIR = "{{config_root}}/{{os()}}" } },
]
