

["_stow:dotfiles"]
hide = true
dir = "{{env.HOME}}/dotfiles"
usage = '''
arg "<pkg>" help="Package types to stow" {
  choices "common" "linux"
  default "commoh"
}
flag "-y --yes" help="Perform simulated operation instead of doing it" {
  global #true
  env "STOW_NO_SIM"
}
'''
run = '''
stow \
  {% if usage.yes %}-v{% else %}--simulate -vv{% endif %} \
  -d {{ env.HOME }}/dotfiles/{{usage.pkg}}/.config \
  -t {{ xdg_config_home }} \
  -R .
'''

["global:stow:doftiles"]
description = "Stow dotfiles"
depends = ["_stow:dotfiles common", "_stow:dotfiles linux"]
run = '''
echo "XDG_CONFIG_HOME: "
eza --icons=always --oneline \
    --no-git --all \
    {{ xdg_config_home }}
'''
