

["_stow:dotfiles"]
hide = true
dir = "{{env.HOME}}/dotfiles"
usage = '''
arg "[target]" {
  help "Target"
  default "{{xdg_config_home}}"
}
flag "-y --yes" {
  help "Perform simulated operation instead of doing it"
  global #true
  env "STOW_NO_SIM"
}
'''
run = '''
stow \
  {% if usage.yes %}-v{% else %}--simulate -vv{% endif %} \
  --target {{ usage.target }} \
  -R .
'''

["global:stow:doftiles"]
description = "Stow dotfiles"
dir = '{{ env.HOME }}/dotfiles'
env = { STOW_NO_SIM = "1" }
run = '''
pushd common/.config || true
mise run _stow:dotfiles
popd

pushd common/.config || true
mise run _stow:dotfiles
popd

echo "XDG_CONFIG_HOME: "
eza --icons=always --oneline \
    --no-git --all \
    {{ xdg_config_home }}
'''


["global:pacman:orphans"]
hide = true
usage = '''
flag "-d --delete"
'''
run = '''
echo 'Orphans:'
pacman -Qdttq
{% if usage.delete %}
pacman -Qdttq | sudo pacman -Rns -
{% endif %}
'''

["global:udev-rules:install"]
hide = true
usage = '''
arg "<rules_file>"
'''
run = '''
sudo cp {{ usage.rules_file }} /etc/udev/rules.d/
sudo udevadm control --reload
'''
