
["twister:find_tests"]
description = "List samples"
tools = { 'yq' = 'latest' }
dir = "{{cwd}}"
run = '''
#!/bin/zsh
fd --strip-cwd-prefix -e yaml -tf '(testcase|sample)\.yaml' \
    -x echo -e \; \
    -x yq e -o tsv '(.tests | with_entries(.key |= "{//}/\(.)") | keys)' '{}'

'''
["twister:testplan:save"]
extends = "twister:testplan"

["twister:testplan:load"]
extends = "twister:testplan"
description = "Load test plan"
vars.testplan_flag = "--load-tests"

["twister:info:list"]
extends = "twister:info"

["twister:info:tree"]
vars.info_flag = '--test-tree'
extends = "twister:info"


# Available log levels for twister: NOTSET,DEBUG,INFO,WARNING,ERROR,CRITICAL

["twister:test:cov"]
description = "Run tests on with coverage (gcovr)."
dir = "{{cwd}}"
usage = '''
arg "<dir>" help="test directory"
arg "<platform>" help="test platform"
'''
run = '''
west twister \
    {{vars.twister_common_flags | default(value='-v -i --no-clean') }} \
    -T {{usage.dir }} \
    -p {{usage.platform}} \
    --enable-coverage \
    --coverage-tool gcovr
'''

# ============================================================================
# On-hardware (target board)
# ============================================================================
["twister:test:hw"]
description = "Run tests on HW"
dir = "{{cwd}}"
usage = '''
arg "<dir>" help="test directory"
arg "<platform>" help="test platform"
'''
run = '''
west twister \
{{vars.twister_common_flags | default(value=['-v', '-i', '--no-clean']) | join(sep=' ') }} \
-T {{usage.dir}} \
-p {{usage.platform}} \
--device-testing \
--west-runner="nrfutil" \
--device-serial="{{vars.SERIAL_PORT | default(value='/dev/ttyACM0') }}" \
--device-flash-with-test --device-flash-timeout=15
'''
["twister:test:size_report"]
description = "Build sh_sdk tests for the aria board and produce ROM/RAM + footprint reports."
dir = "{{cwd}}"
usage = '''
arg "<dir>" help="test directory"
arg "<platform>" help="test platform"
'''
run = '''
west twister \
    {{vars.twister_common_flags | default(value='-v -i --no-clean') }} \
    -T {{usage.dir }} \
    -p {{usage.platform}} \
    --create-rom-ram-report --enable-size-report
'''


