
["global:twister:find_tests"]
description = "List samples"
tools = { 'yq' = 'latest' }
dir = "{{cwd}}"
run = '''
#!/bin/zsh
fd --strip-cwd-prefix -e yaml -tf '(testcase|sample)\.yaml' \
    -x echo -e \; \
    -x yq e -o tsv '(.tests | with_entries(.key |= "{//}/\(.)") | keys)' '{}'

'''
["global:twister:testplan:save"]
extends = "twister:testplan"

["global:twister:testplan:load"]
extends = "twister:testplan"
description = "Load test plan"
vars.testplan_flag = "--load-tests"


# Available log levels for twister: NOTSET,DEBUG,INFO,WARNING,ERROR,CRITICAL

["global:twister:test:cov"]
description = "Run tests on with coverage (gcovr)."
dir = "{{cwd}}"
usage = '''
arg "<dir>" help="test directory"
arg "<platform>" help="test platform"
'''
run = '''
west twister \
    {{vars.twister_common_flags | default(value='-v -i --no-clean') }} \
    -T {{usage.dir }} \
    -p {{usage.platform}} \
    --enable-coverage \
    --coverage-tool gcovr
'''

# ============================================================================
# On-hardware (target board)
# ============================================================================
["global:twister:run:hw"]
description = "Run tests on HW"
extends = 'twister:run'
run = '''
west twister -v \
--inline-logs \
{% if usage.no_clean %} --no-clean {% else %} --clobber-output {% endif %}\
--no-detailed-test-id \
-T {{usage.dir}} \
-p {{usage.board}} \
--enable-slow \
--device-testing \
--device-serial={{usage.serial_port}}{% if usage.flash_script %}--flash-command={{usage.flash_script}}{% endif %} \
{% if usage.outdir %}--outdir={{usage.outdir}}{% endif %} {{ usage.varargs | join(sep=' ') }}
'''

["global:twister:run:sim"]
description = "Run tests on native_sim or othr simulator"
extends = 'twister:run'
run = '''
west twister -v --inline-logs --no-detailed-test-id{% if usage.no_clean %}--no-clean {% else %}--clobber-output{% endif %} \
-T {{usage.dir}} \
-p {{usage.board | default(value='native_sim/native') }} \
{% if usage.outdir %}--outdir={{usage.outdir}} {% endif %}\
{{ usage.varargs | join(sep=' ') }}
'''

["global:twister:test:size_report"]
description = "Build sh_sdk tests for the aria board and produce ROM/RAM + footprint reports."
dir = "{{cwd}}"
usage = '''
arg "<dir>" help="test directory"
arg "<platform>" help="test platform"
'''
run = '''
west twister \
    {{vars.twister_common_flags | default(value='-v -i --no-clean') }} \
    -T {{usage.dir }} \
    -p {{usage.platform}} \
    --create-rom-ram-report --enable-size-report
'''
["global:twister:pytest"]
vars.opts = " --strict-markers --strict-config -ra --twister-harness"
vars.debug_opts = " -v -s --log-cli-level='DEBUG' "
usage = '''
arg "<bdir>"
arg "[varargs]" var=#true
'''
run = '''
pytest {{ vars.opts }} --rootdir=pytest  --build-dir={{usage.bdir}}  --device-type=hardware {{ usage.varargs | join(sep=' ') }}
'''
