
["global:west:info"]
dir = "{{cwd}}"
description = "Get west workspace info"
run = '''
echo "Projects: "
west ls
echo "Workspace status: "
west st
echo "Global Aliases: "
yq e --input-format=ini '.alias' ~/.config/west/config 2>/dev/null
echo "Local Aliases: "
yq e --input-format=ini '.alias' "$(west topdir)/.west/config" 2>/dev/null
'''

["global:west:makeprg"]
dir = "{{cwd}}"
description = "Build a zephyr app with west"
interactive = true
usage = '''
arg "<app>" default="app"
flag "-b --board [board]" env="BOARD"
arg "[varargs]" var=#true double_dash="required"
'''
run = '''
#!/usr/bin/env zsh
west forall \
        -C  "{{cwd}}" \
        manifest \
        -c 'west build -p -b {{usage.board}} {{usage.app}} {{usage.varargs | join(sep=" ")}}'
'''

["global:west:build"]
description = "List samples"
tools = { 'yq' = 'latest' }
dir = "{{cwd}}"
run = '''
#!/bin/zsh
fd --strip-cwd-prefix -e yaml -tf '(testcase|sample)\.yaml' \
    -x echo -e \; \
    -x yq e -o tsv '(.tests | with_entries(.key |= "{//}/\(.)") | keys)' '{}'

'''

["global:west:fd"]
description = "Find file across west workspace and open it with neovim"
interactive = true
alias = "wfd"
dir = "{{cwd}}"
usage = '''
arg "<regex>" help="Regex to find file with fd"
flag "-e --ext [extensions]" help="File extensions, if multiple must be given with ',' separated values"
flag "--rg" help="Use ripgrep --files-with-matches instead of fd"
flag "--agent" help="Flag for agents" {
  long_help """
    Turns off any interactiveness. This task uses a catch all
    double_dash variadic argument the west find output will be piped
    to. If none is given task just print the results
  """
}
arg "[pipe_cmd]" help="Cmd to pipe the output to. Anything after '--' will be piped" {
  var #true
  double_dash "required"
}
'''
run = '''
{% if usage.agent %}
  default_pipe_cmd="cat"
{% else  %}
  default_pipe_cmd="fzf --bind 'enter:become(nvim {})'"
{% endif  %}
if [[ -n "${usage_extensions:-}" ]]; then
  extensions=(${(j:,:)usage_extensions})
fi
eval "pipe_cmd=(${usage_pipe_cmd:-$default_pipe_cmd})"
{% if usage.rg %}
  topdir="$(west topdir 2>/dev/null)"
  rg '{{usage.regex}}' "${topdir:?}" --files-with-matches | "${pipe_cmd[@]}"
{% else  %}
  west -q forall -c "fd '{{usage.regex}}' . --absolute-path ${extensions:+${extensions[@]/#/-e}}" | "${pipe_cmd[@]}"
{% endif  %}

'''
