["global:yq:schema"]
description = "Use yq to get schema of supported file"
dir = '{{cwd}}'
usage = 'arg "<file>"'
run = '''
yq eval '.. | path | join("/")' {{usage.file}}
'''

["global:yq:to_dict"]
description = "Use yq to get a dictionary of all nested data of supported file"
dir = '{{cwd}}'
usage = 'arg "<file>"'
run = '''
yq '.. |(
	( select(kind == "scalar" and parent | kind != "seq") | (path | join("_")) + "='\''" + . + "'\''"),
	( select(kind == "seq") | (path | join("_")) + "=(" + (map("'\''" + . + "'\''") | join(",")) + ")")
)' {{usage.file}}
'''
