# NVIDIA environment variables
env = NVD_BACKEND,direct
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

# Monitors for desktop
monitorv2 {
  output = HDMI-A-1
  mode = preferred
  position = auto-left
  scale = auto
}
monitorv2 {
  output = HDMI-A-2
  mode = preferred
  position = auto-right
  scale = auto
}
workspace = 1,monitor:HDMI-A-1,rounding:true,decorate:true,gapsin:1,gapsout:8
workspace = 2,monitor:HDMI-A-1,rounding:true,decorate:true,gapsin:1,gapsout:8
workspace = 3,monitor:HDMI-A-1,rounding:true,decorate:true,gapsin:1,gapsout:8
workspace = 4,monitor:HDMI-A-2,rounding:true,decorate:true,gapsin:0,gapsout:0
workspace = 5,monitor:HDMI-A-2,rounding:true,decorate:true,gapsin:0,gapsout:0
workspace = 6,monitor:HDMI-A-2,rounding:true,decorate:true,gapsin:0,gapsout:0

